### ISSUE TITLE
WebRTC Connect/Disconnect to any Reality Tab via either Controller mapped button of keyboard interface in Reality Tabs

### ISSUE THREAD

**Issue by NoahSchiffman** [exokitxr/exokit-frontend#53]

**Comment by modulesio** [comment]
I don’t think we are doing anything with WebRTC in the frontend directly. Though of course any reality tab can use it.

Could you clarify the feature request here?

**Comment by NoahSchiffman** [comment]
Oh! well if any Reality Tab can use WebRTC protocol then maybe I didn't need to ask for anything. Close and comment?
