### ISSUE TITLE
error Failed at the exokit@0.0.525 install script.

### ISSUE THREAD

**Issue by NoahSchiffman** [exokitxr/exokit-frontend#56]
![image](https://user-images.githubusercontent.com/37890940/62598189-66779500-b89d-11e9-997f-676c5c40cb05.png)

* error Failed at the exokit@0.0.525 install script.

* 70 error This is probably not a problem with npm. 
* There is likely additional logging output above.

* Additionally, could this be this a problem with GitBash GUI Being installed on my PC, on Windows 10? I have that installed.

* Why is this happening? I thought It was fixed a long time ago.

**Comment by avaer** [comment]
Looks like windows build tools are missing. Which build instructions are being followed?

Also, is this an exokit issue or a frontend issue?

**Comment by NoahSchiffman** [comment]
it was me trying to run `npm i`. Also, how do I install them?  I'm checking documentation now.

**Comment by NoahSchiffman** [comment]
`npm install -g windows-build-tools` - Got it! installing!

**Comment by avaer** [comment]
Yup, that's one way. https://github.com/exokitxr/exokit/blob/master/BUILDING.md

**Comment by modulesio** [comment]
Yup, that's one way. https://github.com/exokitxr/exokit/blob/master/BUILDING.md

**Comment by avaer** [comment]
Awesome. Closing this issue in the mean time -- mostly because it's not `exokit-frontend` related.
